"""LangGraph-based multi-agent voting over Pareto-front scenarios.

The module provides a notebook-friendly API for selecting one scenario from a
Pareto frontier using three stakeholder agents:

* administration
* residents
* investor

Each stakeholder is implemented as a LangGraph ReAct agent with deterministic
tools over the frontier. Agents return strict JSON that is validated with
Pydantic and ``JsonOutputParser``. A graph-level aggregator then computes the
final winner by majority vote with Borda and confidence tie-breakers.
"""

from __future__ import annotations

import json
import math
import re
from collections import Counter
from typing import Any, Literal, Mapping, Sequence

import pandas as pd
from langchain.agents import create_agent
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_core.tools import tool
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing_extensions import TypedDict


StakeholderName = Literal["administration", "residents", "investor"]


ROLE_BRIEFS: dict[StakeholderName, str] = {
    "administration": (
        "Смотри на общественную пользу, бюджетную устойчивость, налоговую базу, рабочие места, "
        "транспортную связность, реализуемость, социальную инфраструктуру, экологические риски "
        "и политическую приемлемость."
    ),
    "residents": (
        "Смотри на качество жизни, доступность жилья и сервисов, шум, экологию, озеленение, "
        "безопасность, walkability, нагрузку на инфраструктуру и повседневный комфорт."
    ),
    "investor": (
        "Смотри на доходность, скорость реализации, спрос, ликвидность, CAPEX/OPEX, риски, "
        "простоту согласований, коммерческий потенциал и вероятность окупаемости."
    ),
}

ROLE_DISPLAY_NAMES: dict[StakeholderName, str] = {
    "administration": "Администрация",
    "residents": "Жители",
    "investor": "Инвестор",
}

SCENARIO_ID_CANDIDATES = ("scenario_id", "id", "scenario", "name", "label")
TITLE_CANDIDATES = ("title", "name", "scenario_name", "label")
SUMMARY_CANDIDATES = ("summary", "description", "scenario_description", "rationale")


def _format_money(value: Any) -> str:
    """Format money-like values for autogenerated summaries."""
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if math.isnan(numeric) or math.isinf(numeric):
        return "n/a"
    return f"{numeric:,.0f} ₽".replace(",", " ")


def _scenario_summary_from_row(
    *,
    scenario_id: str,
    title: str,
    land_use: Any = None,
    land_value_gain: Any = None,
    investor_npv: Any = None,
) -> str:
    """Build a compact text summary when an explicit summary column is absent."""
    parts = [title or f"Сценарий {scenario_id}"]
    if land_use not in (None, "", "nan"):
        parts.append(f"land_use={land_use}")
    if land_value_gain is not None:
        parts.append(f"прирост стоимости земли={_format_money(land_value_gain)}")
    if investor_npv is not None:
        parts.append(f"NPV инвестора={_format_money(investor_npv)}")
    return "; ".join(parts)


class ParetoScenario(BaseModel):
    """Canonical representation of one Pareto-front scenario."""

    model_config = ConfigDict(extra="forbid")

    scenario_id: str = Field(description="Unique scenario identifier.")
    title: str = Field(default="", description="Short human-readable title.")
    summary: str = Field(default="", description="One-paragraph scenario summary.")
    metrics: dict[str, float | int | bool | str | None] = Field(
        default_factory=dict,
        description="Scenario KPIs used during decision-making.",
    )
    pros: list[str] = Field(default_factory=list)
    cons: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("scenario_id", mode="before")
    @classmethod
    def _coerce_scenario_id(cls, value: Any) -> str:
        text = str(value).strip()
        if not text:
            raise ValueError("scenario_id cannot be empty")
        return text

    @field_validator("title", "summary", mode="before")
    @classmethod
    def _coerce_text(cls, value: Any) -> str:
        if value is None:
            return ""
        return str(value).strip()


class StakeholderVote(BaseModel):
    """Structured JSON returned by each stakeholder agent."""

    model_config = ConfigDict(extra="forbid")

    stakeholder: StakeholderName
    selected_scenario_id: str = Field(description="Scenario chosen by the stakeholder.")
    ranking: list[str] = Field(
        default_factory=list,
        description="Scenarios ordered from best to worst from this stakeholder's perspective.",
    )
    rationale: str = Field(description="Short explanation of the vote.")
    main_tradeoffs: list[str] = Field(default_factory=list)
    metrics_considered: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in the vote from 0 to 1.")
    used_tools: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def _ensure_selected_in_ranking(self) -> "StakeholderVote":
        ranking = [str(item).strip() for item in self.ranking if str(item).strip()]
        if not ranking:
            ranking = [self.selected_scenario_id]
        if self.selected_scenario_id not in ranking:
            ranking.insert(0, self.selected_scenario_id)
        if ranking[0] != self.selected_scenario_id:
            ranking = [self.selected_scenario_id, *[item for item in ranking if item != self.selected_scenario_id]]
        self.ranking = ranking
        return self


class ParetoVotingResult(BaseModel):
    """Final structured result of the multi-agent vote."""

    model_config = ConfigDict(extra="forbid")

    winner_scenario_id: str
    winner_title: str = ""
    winner_summary: str = ""
    winner_metrics: dict[str, float | int | bool | str | None] = Field(default_factory=dict)
    winner_metadata: dict[str, Any] = Field(default_factory=dict)
    winner_interpretation: str = ""
    frontier_size: int
    vote_counts: dict[str, int]
    borda_scores: dict[str, float]
    confidence_scores: dict[str, float]
    tie_break_method: Literal["majority", "borda", "confidence", "single_agent"]
    consensus_summary: str
    votes: list[StakeholderVote]
    scenario_ids: list[str]


class WinnerScenarioQAResult(BaseModel):
    """Structured answer for follow-up questions about the winning scenario only."""

    model_config = ConfigDict(extra="forbid")

    question: str
    answer: str
    key_points: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)


class ParetoVotingState(TypedDict, total=False):
    """State passed through the LangGraph voting workflow."""

    administration_vote: dict[str, Any]
    residents_vote: dict[str, Any]
    investor_vote: dict[str, Any]
    result: dict[str, Any]


def _json_ready(value: Any) -> Any:
    """Convert values to JSON-safe primitives."""
    if value is None:
        return None
    if isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
        return value
    if isinstance(value, (pd.Timestamp, pd.Timedelta)):
        return str(value)
    if hasattr(value, "item"):
        try:
            return _json_ready(value.item())
        except Exception:
            return str(value)
    if isinstance(value, Mapping):
        return {str(key): _json_ready(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_ready(item) for item in value]
    return str(value)


def _strip_code_fences(text: str) -> str:
    """Remove common markdown fences around JSON content."""
    cleaned = text.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    return cleaned.strip()


def _message_to_text(message: BaseMessage | Any) -> str:
    """Extract plain text from LangChain message content."""
    if isinstance(message, str):
        return message
    content = getattr(message, "content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        chunks: list[str] = []
        for item in content:
            if isinstance(item, str):
                chunks.append(item)
            elif isinstance(item, Mapping):
                text = item.get("text")
                if text:
                    chunks.append(str(text))
        return "\n".join(chunks).strip()
    return str(content)


def _extract_used_tools(messages: Sequence[BaseMessage]) -> list[str]:
    """Collect tool names that were called during agent execution."""
    used_tools: list[str] = []
    for message in messages:
        if isinstance(message, AIMessage):
            for tool_call in getattr(message, "tool_calls", []) or []:
                name = tool_call.get("name")
                if name and name not in used_tools:
                    used_tools.append(name)
    return used_tools


def _infer_column(columns: Sequence[str], candidates: Sequence[str]) -> str | None:
    lowered = {column.lower(): column for column in columns}
    for candidate in candidates:
        if candidate in lowered:
            return lowered[candidate]
    return None


def collect_pareto_scenarios(
    frontier: pd.DataFrame | Sequence[Mapping[str, Any]] | Sequence[ParetoScenario],
    *,
    scenario_id_column: str | None = None,
    title_column: str | None = None,
    summary_column: str | None = None,
    metric_columns: Sequence[str] | None = None,
    pros_column: str | None = None,
    cons_column: str | None = None,
    metadata_columns: Sequence[str] | None = None,
) -> list[ParetoScenario]:
    """Normalize a DataFrame or list of dictionaries into ``ParetoScenario`` objects."""
    if isinstance(frontier, pd.DataFrame):
        df = frontier.copy()
        scenario_id_column = scenario_id_column or _infer_column(df.columns, SCENARIO_ID_CANDIDATES)
        if scenario_id_column is None:
            scenario_id_column = "scenario_id"
            df[scenario_id_column] = df.index.astype(str)

        title_column = title_column or _infer_column(df.columns, TITLE_CANDIDATES)
        summary_column = summary_column or _infer_column(df.columns, SUMMARY_CANDIDATES)
        excluded = {scenario_id_column, title_column, summary_column, pros_column, cons_column, "geometry"}

        if metric_columns is None:
            metric_columns = [
                column
                for column in df.columns
                if column not in excluded and pd.api.types.is_numeric_dtype(df[column])
            ]
        if metadata_columns is None:
            metadata_columns = [
                column
                for column in df.columns
                if column not in excluded and column not in metric_columns
            ]

        scenarios: list[ParetoScenario] = []
        for _, row in df.iterrows():
            title = row.get(title_column, "") if title_column else ""
            summary = row.get(summary_column, "") if summary_column else ""
            if not summary:
                summary = _scenario_summary_from_row(
                    scenario_id=str(row[scenario_id_column]),
                    title=title or str(row[scenario_id_column]),
                    land_use=row.get("land_use"),
                    land_value_gain=row.get("land_value_gain"),
                    investor_npv=row.get("investor_npv"),
                )
            pros = row.get(pros_column, []) if pros_column else []
            cons = row.get(cons_column, []) if cons_column else []
            scenarios.append(
                ParetoScenario(
                    scenario_id=row[scenario_id_column],
                    title=title or str(row[scenario_id_column]),
                    summary=summary,
                    metrics={column: _json_ready(row[column]) for column in metric_columns},
                    pros=list(pros) if isinstance(pros, list) else ([str(pros)] if pros else []),
                    cons=list(cons) if isinstance(cons, list) else ([str(cons)] if cons else []),
                    metadata={column: _json_ready(row[column]) for column in metadata_columns},
                )
            )
        return scenarios

    scenarios = []
    for item in frontier:
        if isinstance(item, ParetoScenario):
            scenarios.append(item)
        else:
            payload = dict(item)
            scenarios.append(ParetoScenario.model_validate(payload))
    return scenarios


def _build_scenario_index(scenarios: Sequence[ParetoScenario]) -> dict[str, ParetoScenario]:
    index = {scenario.scenario_id: scenario for scenario in scenarios}
    if len(index) != len(scenarios):
        raise ValueError("Scenario identifiers must be unique inside the Pareto frontier.")
    return index


def _numeric_metric_ranges(scenarios: Sequence[ParetoScenario]) -> dict[str, tuple[float, float]]:
    values_by_metric: dict[str, list[float]] = {}
    for scenario in scenarios:
        for metric, value in scenario.metrics.items():
            if isinstance(value, bool):
                numeric = float(value)
            elif isinstance(value, (int, float)) and not isinstance(value, bool):
                if math.isnan(float(value)) or math.isinf(float(value)):
                    continue
                numeric = float(value)
            else:
                continue
            values_by_metric.setdefault(metric, []).append(numeric)
    return {
        metric: (min(values), max(values))
        for metric, values in values_by_metric.items()
        if values
    }


def _build_tools(scenarios: Sequence[ParetoScenario]):
    scenario_index = _build_scenario_index(scenarios)
    metric_ranges = _numeric_metric_ranges(scenarios)

    @tool
    def list_pareto_scenarios() -> str:
        """Return a compact JSON list of all scenarios in the Pareto frontier."""
        payload = [
            {
                "scenario_id": scenario.scenario_id,
                "title": scenario.title,
                "summary": scenario.summary,
                "metrics": scenario.metrics,
                "metadata_preview": {
                    key: scenario.metadata.get(key)
                    for key in ("land_use", "params_repaired")
                    if key in scenario.metadata
                },
            }
            for scenario in scenarios
        ]
        return json.dumps(payload, ensure_ascii=False, indent=2)

    @tool
    def get_scenario_details(scenario_id: str) -> str:
        """Return full JSON details for one scenario by its identifier."""
        scenario = scenario_index.get(str(scenario_id).strip())
        if scenario is None:
            return json.dumps(
                {
                    "error": f"Scenario '{scenario_id}' not found.",
                    "available_scenarios": sorted(scenario_index),
                },
                ensure_ascii=False,
                indent=2,
            )
        return json.dumps(scenario.model_dump(), ensure_ascii=False, indent=2)

    @tool
    def compare_scenarios(scenario_ids: list[str] | None = None) -> str:
        """Compare scenarios and return metric values with min/max context for each metric."""
        selected = scenarios
        if scenario_ids:
            missing = [item for item in scenario_ids if item not in scenario_index]
            if missing:
                return json.dumps(
                    {
                        "error": "Unknown scenario ids.",
                        "missing": missing,
                        "available_scenarios": sorted(scenario_index),
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            selected = [scenario_index[item] for item in scenario_ids]

        metrics_payload: dict[str, Any] = {}
        for metric, (min_value, max_value) in metric_ranges.items():
            metric_values = {
                scenario.scenario_id: scenario.metrics.get(metric)
                for scenario in selected
                if metric in scenario.metrics
            }
            if not metric_values:
                continue
            sortable = [(scenario_id, float(value)) for scenario_id, value in metric_values.items() if value is not None]
            metrics_payload[metric] = {
                "min": min_value,
                "max": max_value,
                "values": metric_values,
                "rank_high_to_low": [scenario_id for scenario_id, _ in sorted(sortable, key=lambda item: item[1], reverse=True)],
                "rank_low_to_high": [scenario_id for scenario_id, _ in sorted(sortable, key=lambda item: item[1])],
            }

        payload = {
            "scenario_ids": [scenario.scenario_id for scenario in selected],
            "metric_context": metrics_payload,
        }
        return json.dumps(payload, ensure_ascii=False, indent=2)

    @tool
    def score_scenarios(
        prefer_high_metrics: list[str],
        prefer_low_metrics: list[str],
        weights: dict[str, float] | None = None,
        scenario_ids: list[str] | None = None,
    ) -> str:
        """Compute a weighted normalized score over numeric metrics for the selected scenarios."""
        selected = scenarios if not scenario_ids else [scenario_index[item] for item in scenario_ids if item in scenario_index]
        if not selected:
            return json.dumps({"error": "No scenarios selected for scoring."}, ensure_ascii=False, indent=2)

        weights = {metric: float(value) for metric, value in (weights or {}).items()}
        relevant_metrics = list(dict.fromkeys([*prefer_high_metrics, *prefer_low_metrics]))
        scores: dict[str, float] = {scenario.scenario_id: 0.0 for scenario in selected}
        metric_breakdown: dict[str, dict[str, float | None]] = {}

        for metric in relevant_metrics:
            if metric not in metric_ranges:
                metric_breakdown[metric] = {scenario.scenario_id: None for scenario in selected}
                continue

            min_value, max_value = metric_ranges[metric]
            span = max_value - min_value
            weight = weights.get(metric, 1.0)
            metric_breakdown[metric] = {}
            for scenario in selected:
                raw_value = scenario.metrics.get(metric)
                if raw_value is None:
                    metric_breakdown[metric][scenario.scenario_id] = None
                    continue

                numeric_value = float(raw_value)
                if span <= 0:
                    normalized = 1.0
                else:
                    normalized = (numeric_value - min_value) / span
                if metric in prefer_low_metrics:
                    normalized = 1.0 - normalized
                metric_breakdown[metric][scenario.scenario_id] = round(normalized, 6)
                scores[scenario.scenario_id] += normalized * weight

        ranked = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        payload = {
            "scenario_ids": [scenario.scenario_id for scenario in selected],
            "scores": {scenario_id: round(score, 6) for scenario_id, score in scores.items()},
            "ranking": [scenario_id for scenario_id, _ in ranked],
            "metric_breakdown": metric_breakdown,
        }
        return json.dumps(payload, ensure_ascii=False, indent=2)

    return [list_pareto_scenarios, get_scenario_details, compare_scenarios, score_scenarios]


def _repair_json_with_llm(
    *,
    llm,
    parser: JsonOutputParser,
    raw_text: str,
    error_text: str,
) -> Any:
    """Ask the model to repair invalid JSON according to parser instructions."""
    repair_prompt = PromptTemplate(
        template=(
            "Исправь ответ модели так, чтобы он стал строго валидным JSON по заданной схеме.\n"
            "Верни только JSON, без markdown и комментариев.\n"
            "Все текстовые поля внутри JSON должны быть только на русском языке. "
            "Английский допустим только для `scenario_id`, имён метрик, технических ключей и исходных кодов land-use.\n\n"
            "Ошибка парсинга:\n{error_text}\n\n"
            "Исходный ответ:\n{raw_text}\n\n"
            "{format_instructions}"
        ),
        input_variables=["error_text", "raw_text"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )
    repaired = llm.invoke(repair_prompt.format(error_text=error_text, raw_text=raw_text))
    return parser.parse(_strip_code_fences(_message_to_text(repaired)))


def _parse_agent_json(
    *,
    llm,
    parser: JsonOutputParser,
    raw_text: str,
    max_retries: int,
) -> Any:
    """Parse agent JSON and retry through a repair prompt if needed."""
    candidate = _strip_code_fences(raw_text)
    try:
        return parser.parse(candidate)
    except Exception as exc:
        last_error = exc
    for _ in range(max_retries):
        try:
            return _repair_json_with_llm(
                llm=llm,
                parser=parser,
                raw_text=candidate,
                error_text=str(last_error),
            )
        except Exception as exc:
            last_error = exc
    raise ValueError(f"Unable to parse valid JSON from agent response: {last_error}") from last_error


def _borda_scores(votes: Sequence[StakeholderVote], scenario_ids: Sequence[str]) -> dict[str, float]:
    scores = {scenario_id: 0.0 for scenario_id in scenario_ids}
    base = len(scenario_ids)
    for vote in votes:
        for index, scenario_id in enumerate(vote.ranking):
            if scenario_id in scores:
                scores[scenario_id] += float(base - index)
    return {scenario_id: round(score, 6) for scenario_id, score in scores.items()}


def _confidence_scores(votes: Sequence[StakeholderVote], scenario_ids: Sequence[str]) -> dict[str, float]:
    scores = {scenario_id: 0.0 for scenario_id in scenario_ids}
    for vote in votes:
        scores[vote.selected_scenario_id] += vote.confidence
    return {scenario_id: round(score, 6) for scenario_id, score in scores.items()}


def _determine_winner(votes: Sequence[StakeholderVote], scenario_ids: Sequence[str]) -> tuple[str, str, dict[str, int], dict[str, float], dict[str, float]]:
    vote_counts = Counter(vote.selected_scenario_id for vote in votes)
    for scenario_id in scenario_ids:
        vote_counts.setdefault(scenario_id, 0)

    top_vote_count = max(vote_counts.values()) if vote_counts else 0
    winners = [scenario_id for scenario_id, count in vote_counts.items() if count == top_vote_count]
    if len(winners) == 1:
        borda = _borda_scores(votes, scenario_ids)
        confidence = _confidence_scores(votes, scenario_ids)
        return winners[0], "majority", dict(vote_counts), borda, confidence

    borda = _borda_scores(votes, scenario_ids)
    top_borda = max(borda[scenario_id] for scenario_id in winners)
    borda_winners = [scenario_id for scenario_id in winners if borda[scenario_id] == top_borda]
    if len(borda_winners) == 1:
        confidence = _confidence_scores(votes, scenario_ids)
        return borda_winners[0], "borda", dict(vote_counts), borda, confidence

    confidence = _confidence_scores(votes, scenario_ids)
    top_confidence = max(confidence[scenario_id] for scenario_id in borda_winners)
    confidence_winners = [scenario_id for scenario_id in borda_winners if confidence[scenario_id] == top_confidence]
    if len(confidence_winners) == 1:
        return confidence_winners[0], "confidence", dict(vote_counts), borda, confidence

    final_winner = sorted(confidence_winners)[0]
    return final_winner, "confidence", dict(vote_counts), borda, confidence


def _build_winner_interpretation(
    *,
    winner: ParetoScenario,
    votes: Sequence[StakeholderVote],
) -> str:
    """Create a short human-readable interpretation of why the winner was selected."""
    rationale_parts: list[str] = []
    stakeholder_votes = [vote for vote in votes if vote.selected_scenario_id == winner.scenario_id]

    if "land_value_gain" in winner.metrics:
        rationale_parts.append(
            f"прирост стоимости земли {_format_money(winner.metrics.get('land_value_gain'))}"
        )
    if "investor_npv" in winner.metrics:
        rationale_parts.append(
            f"NPV инвестора {_format_money(winner.metrics.get('investor_npv'))}"
        )
    if winner.metadata.get("land_use"):
        rationale_parts.append(f"доминирующий land_use={winner.metadata['land_use']}")

    rationale_text = ", ".join(rationale_parts) if rationale_parts else winner.summary or winner.title

    if stakeholder_votes:
        support_text = "; ".join(
            f"{ROLE_DISPLAY_NAMES[vote.stakeholder]}: {vote.rationale}"
            for vote in stakeholder_votes
        )
        return (
            f"Сценарий {winner.scenario_id} выбран, потому что он лучше балансирует интересы сторон: "
            f"{rationale_text}. Поддержавшие стороны объяснили выбор так: {support_text}"
        )

    all_votes_text = "; ".join(
        f"{ROLE_DISPLAY_NAMES[vote.stakeholder]} выбрал {vote.selected_scenario_id}: {vote.rationale}"
        for vote in votes
    )
    return (
        f"Сценарий {winner.scenario_id} победил после агрегирования голосов. "
        f"Ключевые характеристики: {rationale_text}. Голоса сторон: {all_votes_text}"
    )


def _format_result_for_console(result: ParetoVotingResult) -> str:
    """Format the voting result for notebook/console output."""
    lines = [
        "Лучший сценарий",
        f" • ID: {result.winner_scenario_id}",
    ]
    if result.winner_title:
        lines.append(f" • Название: {result.winner_title}")
    if result.winner_summary:
        lines.append(f" • Summary: {result.winner_summary}")
    if result.winner_metrics:
        metrics_text = ", ".join(
            f"{key}={value}"
            for key, value in result.winner_metrics.items()
        )
        lines.append(f" • Метрики: {metrics_text}")
    lines.append("")
    lines.append("Почему выбран")
    lines.append(f" • {result.winner_interpretation or result.consensus_summary}")
    lines.append("")
    lines.append("Голоса")
    for vote in result.votes:
        lines.append(
            f" • {ROLE_DISPLAY_NAMES[vote.stakeholder]} -> {vote.selected_scenario_id}: {vote.rationale}"
        )
    return "\n".join(lines)


def _format_qa_result_for_console(result: WinnerScenarioQAResult) -> str:
    """Format a follow-up QA response for notebook/console output."""
    lines = [
        "Ответ по выбранному сценарию",
        f" • Вопрос: {result.question}",
        f" • Ответ: {result.answer}",
    ]
    if result.key_points:
        lines.append("")
        lines.append("Ключевые пункты")
        for item in result.key_points:
            lines.append(f" • {item}")
    if result.evidence:
        lines.append("")
        lines.append("Основание ответа")
        for item in result.evidence:
            lines.append(f" • {item}")
    if result.limitations:
        lines.append("")
        lines.append("Ограничения")
        for item in result.limitations:
            lines.append(f" • {item}")
    return "\n".join(lines)


class ParetoMultiAgentOrchestrator:
    """Run three stakeholder ReAct agents over the Pareto frontier."""

    def __init__(
        self,
        *,
        llm,
        max_retries: int = 2,
        debug: bool = False,
        additional_context: str = "",
        stakeholder_briefs: Mapping[StakeholderName, str] | None = None,
    ) -> None:
        self.llm = llm
        self.max_retries = max_retries
        self.debug = debug
        self.additional_context = additional_context.strip()
        self.stakeholder_briefs = {**ROLE_BRIEFS, **dict(stakeholder_briefs or {})}

    def _vote_parser(self) -> JsonOutputParser:
        return JsonOutputParser(pydantic_object=StakeholderVote)

    def _build_agent(self, *, stakeholder: StakeholderName, tools):
        parser = self._vote_parser()
        system_prompt = (
            f"Ты агент-эксперт, представляющий сторону '{ROLE_DISPLAY_NAMES[stakeholder]}'. "
            "Ты выбираешь лучший вариант из парето-фронта. "
            "Сначала используй инструменты для анализа. Не придумывай факты и не ссылайся на метрики, "
            "которых нет в данных. Если в сценариях присутствуют поля `land_value_gain`, "
            "`investor_npv` и `params_repaired`, обязательно учитывай их. "
            "Финальный ответ верни только в JSON. "
            "Все текстовые поля JSON (`rationale`, элементы `main_tradeoffs`, элементы `metrics_considered`) "
            "пиши только на русском языке. "
            "Английский допустим только для `scenario_id`, имён метрик, технических ключей и исходных кодов land-use. "
            f"Приоритеты стороны: {self.stakeholder_briefs[stakeholder]}\n\n"
            f"{parser.get_format_instructions()}"
        )
        return create_agent(
            model=self.llm,
            tools=tools,
            system_prompt=system_prompt,
            debug=self.debug,
            name=f"{stakeholder}_react_agent",
        )

    def _role_prompt(self, *, stakeholder: StakeholderName, scenario_ids: Sequence[str]) -> str:
        prompt = PromptTemplate(
            template=(
                "У тебя есть парето-фронт из {frontier_size} сценариев: {scenario_ids}.\n"
                "Нужно выбрать ровно один лучший сценарий для стороны '{stakeholder}'.\n"
                "Обязательно используй хотя бы один инструмент перед финальным ответом.\n"
                "Если доступны `land_value_gain`, `investor_npv` и `params_repaired`, "
                "используй их как ключевые входные данные.\n"
                "Все текстовые объяснения и выводы пиши только на русском языке.\n"
                "Верни только JSON по схеме ниже.\n\n"
                "Приоритеты стороны:\n{stakeholder_brief}\n\n"
                "{additional_context}\n\n"
                "{format_instructions}"
            ),
            input_variables=["frontier_size", "scenario_ids", "stakeholder", "stakeholder_brief", "additional_context"],
            partial_variables={"format_instructions": self._vote_parser().get_format_instructions()},
        )
        return prompt.format(
            frontier_size=len(scenario_ids),
            scenario_ids=", ".join(scenario_ids),
            stakeholder=stakeholder,
            stakeholder_brief=self.stakeholder_briefs[stakeholder],
            additional_context=self.additional_context or "Дополнительный контекст не задан.",
        )

    def _run_stakeholder(
        self,
        *,
        stakeholder: StakeholderName,
        scenarios: Sequence[ParetoScenario],
    ) -> StakeholderVote:
        parser = self._vote_parser()
        tools = _build_tools(scenarios)
        agent = self._build_agent(stakeholder=stakeholder, tools=tools)
        scenario_ids = [scenario.scenario_id for scenario in scenarios]
        result = agent.invoke({"messages": [HumanMessage(content=self._role_prompt(stakeholder=stakeholder, scenario_ids=scenario_ids))]})
        messages = result["messages"]
        raw_text = _message_to_text(messages[-1])
        payload = _parse_agent_json(
            llm=self.llm,
            parser=parser,
            raw_text=raw_text,
            max_retries=self.max_retries,
        )
        vote = StakeholderVote.model_validate(payload)
        vote.used_tools = _extract_used_tools(messages)

        unknown_ids = [scenario_id for scenario_id in vote.ranking if scenario_id not in scenario_ids]
        if vote.selected_scenario_id not in scenario_ids:
            raise ValueError(
                f"Stakeholder '{stakeholder}' selected unknown scenario_id '{vote.selected_scenario_id}'."
            )
        if unknown_ids:
            vote.ranking = [scenario_id for scenario_id in vote.ranking if scenario_id in scenario_ids]
            if vote.selected_scenario_id not in vote.ranking:
                vote.ranking.insert(0, vote.selected_scenario_id)
        return vote

    def _build_graph(self, scenarios: Sequence[ParetoScenario]):
        graph = StateGraph(ParetoVotingState)

        def administration_node(_: ParetoVotingState) -> ParetoVotingState:
            vote = self._run_stakeholder(stakeholder="administration", scenarios=scenarios)
            return {"administration_vote": vote.model_dump()}

        def residents_node(state: ParetoVotingState) -> ParetoVotingState:
            vote = self._run_stakeholder(stakeholder="residents", scenarios=scenarios)
            return {
                "administration_vote": state.get("administration_vote", {}),
                "residents_vote": vote.model_dump(),
            }

        def investor_node(state: ParetoVotingState) -> ParetoVotingState:
            vote = self._run_stakeholder(stakeholder="investor", scenarios=scenarios)
            return {
                "administration_vote": state.get("administration_vote", {}),
                "residents_vote": state.get("residents_vote", {}),
                "investor_vote": vote.model_dump(),
            }

        def aggregate_node(state: ParetoVotingState) -> ParetoVotingState:
            votes = [
                StakeholderVote.model_validate(state["administration_vote"]),
                StakeholderVote.model_validate(state["residents_vote"]),
                StakeholderVote.model_validate(state["investor_vote"]),
            ]
            scenario_ids = [scenario.scenario_id for scenario in scenarios]
            scenario_index = _build_scenario_index(scenarios)
            winner_id, tie_break_method, vote_counts, borda_scores, confidence_scores = _determine_winner(
                votes,
                scenario_ids,
            )
            winner = scenario_index[winner_id]
            winner_interpretation = _build_winner_interpretation(
                winner=winner,
                votes=votes,
            )
            consensus_summary = (
                f"Победил сценарий {winner_id}. Голоса: "
                + ", ".join(
                    f"{ROLE_DISPLAY_NAMES[vote.stakeholder]} -> {vote.selected_scenario_id}"
                    for vote in votes
                )
                + f". Метод выбора победителя: {tie_break_method}."
            )
            result = ParetoVotingResult(
                winner_scenario_id=winner_id,
                winner_title=winner.title,
                winner_summary=winner.summary,
                winner_metrics=winner.metrics,
                winner_metadata=winner.metadata,
                winner_interpretation=winner_interpretation,
                frontier_size=len(scenarios),
                vote_counts=vote_counts,
                borda_scores=borda_scores,
                confidence_scores=confidence_scores,
                tie_break_method=tie_break_method,
                consensus_summary=consensus_summary,
                votes=votes,
                scenario_ids=scenario_ids,
            )
            return {
                "administration_vote": state["administration_vote"],
                "residents_vote": state["residents_vote"],
                "investor_vote": state["investor_vote"],
                "result": result.model_dump(),
            }

        graph.add_node("administration", administration_node)
        graph.add_node("residents", residents_node)
        graph.add_node("investor", investor_node)
        graph.add_node("aggregate", aggregate_node)
        graph.add_edge(START, "administration")
        graph.add_edge("administration", "residents")
        graph.add_edge("residents", "investor")
        graph.add_edge("investor", "aggregate")
        graph.add_edge("aggregate", END)
        return graph.compile()

    def invoke(
        self,
        frontier: pd.DataFrame | Sequence[Mapping[str, Any]] | Sequence[ParetoScenario],
        **collect_kwargs: Any,
    ) -> ParetoVotingResult:
        """Run the full graph and return a validated structured result."""
        scenarios = collect_pareto_scenarios(frontier, **collect_kwargs)
        if not scenarios:
            raise ValueError("Pareto frontier is empty.")
        compiled = self._build_graph(scenarios)
        state = compiled.invoke({})
        return ParetoVotingResult.model_validate(state["result"])

    run = invoke


def run_pareto_vote(
    frontier: pd.DataFrame | Sequence[Mapping[str, Any]] | Sequence[ParetoScenario],
    *,
    llm,
    max_retries: int = 2,
    debug: bool = False,
    print_result: bool = True,
    additional_context: str = "",
    stakeholder_briefs: Mapping[StakeholderName, str] | None = None,
    **collect_kwargs: Any,
) -> ParetoVotingResult:
    """Neutral notebook-friendly entrypoint for multi-agent Pareto voting."""
    result = select_best_pareto_scenario_multiagent(
        frontier,
        llm=llm,
        max_retries=max_retries,
        debug=debug,
        additional_context=additional_context,
        stakeholder_briefs=stakeholder_briefs,
        **collect_kwargs,
    )
    if print_result:
        print(_format_result_for_console(result))
    return result


def ask_winner_scenario_question(
    *,
    result: ParetoVotingResult,
    llm,
    question: str,
    print_result: bool = True,
) -> WinnerScenarioQAResult:
    """Answer a follow-up question using only the winning scenario context."""
    parser = JsonOutputParser(pydantic_object=WinnerScenarioQAResult)
    winner_context = {
        "winner_scenario_id": result.winner_scenario_id,
        "winner_title": result.winner_title,
        "winner_summary": result.winner_summary,
        "winner_metrics": result.winner_metrics,
        "winner_metadata": result.winner_metadata,
        "winner_interpretation": result.winner_interpretation,
        "vote_counts": result.vote_counts,
        "votes": [vote.model_dump() for vote in result.votes],
    }
    prompt = PromptTemplate(
        template=(
            "Ответь на вопрос только по выбранному победившему сценарию.\n"
            "Запрещено ссылаться на другие сценарии, если их данные не даны в контексте ниже.\n"
            "Если данных недостаточно, прямо скажи об этом в `limitations` и не выдумывай факты.\n"
            "Все текстовые поля должны быть только на русском языке.\n\n"
            "Контекст победившего сценария:\n{winner_context}\n\n"
            "Вопрос:\n{question}\n\n"
            "{format_instructions}"
        ),
        input_variables=["winner_context", "question"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )
    response = llm.invoke(
        prompt.format(
            winner_context=json.dumps(winner_context, ensure_ascii=False, indent=2),
            question=question,
        )
    )
    payload = _parse_agent_json(
        llm=llm,
        parser=parser,
        raw_text=_message_to_text(response),
        max_retries=2,
    )
    qa_result = WinnerScenarioQAResult.model_validate(payload)
    if print_result:
        print(_format_qa_result_for_console(qa_result))
    return qa_result


def select_best_pareto_scenario_multiagent(
    frontier: pd.DataFrame | Sequence[Mapping[str, Any]] | Sequence[ParetoScenario],
    *,
    llm,
    max_retries: int = 2,
    debug: bool = False,
    additional_context: str = "",
    stakeholder_briefs: Mapping[StakeholderName, str] | None = None,
    **collect_kwargs: Any,
) -> ParetoVotingResult:
    """Notebook-friendly wrapper for the three-agent LangGraph vote."""
    orchestrator = ParetoMultiAgentOrchestrator(
        llm=llm,
        max_retries=max_retries,
        debug=debug,
        additional_context=additional_context,
        stakeholder_briefs=stakeholder_briefs,
    )
    return orchestrator.invoke(frontier, **collect_kwargs)


def select_best_pareto_scenario(
    frontier: pd.DataFrame | Sequence[Mapping[str, Any]] | Sequence[ParetoScenario],
    *,
    llm,
    **kwargs: Any,
) -> str:
    """Return only the winning scenario identifier."""
    result = select_best_pareto_scenario_multiagent(frontier, llm=llm, **kwargs)
    return result.winner_scenario_id


__all__ = [
    "ParetoScenario",
    "StakeholderVote",
    "ParetoVotingResult",
    "WinnerScenarioQAResult",
    "ParetoMultiAgentOrchestrator",
    "ask_winner_scenario_question",
    "collect_pareto_scenarios",
    "run_pareto_vote",
    "select_best_pareto_scenario",
    "select_best_pareto_scenario_multiagent",
]
